name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Clone or update repo on EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            if [ ! -d ~/sample.daytrader7 ]; then
              git clone https://github.com/narayan1989-bais/sample.daytrader7.git
            else
              cd ~/sample.daytrader7
              git pull origin main
            fi
          EOF

      - name: Build the project on EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} "cd ~/sample.daytrader7 && mvn install"

      - name: Start Liberty server on EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} "cd ~/sample.daytrader7/daytrader-ee7 && nohup mvn liberty:run > liberty.log 2>&1 &"
