name: Simple SSH to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:   # <--- manual trigger enabled here

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: SSH and create directory and file on EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            mkdir -p ~/test-directory
            echo "This is a test file" > ~/test-directory/test-file.txt
          EOF
